package dev.jeval.metrics;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.jeval.EvaluationModel;
import dev.jeval.LlmTestCase;
import dev.jeval.Metric;
import dev.jeval.MetricResult;
import dev.jeval.SingleTurnParam;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class JsonCorrectnessMetric implements Metric {
    public static final String DEFAULT_CORRECT_REASON =
            "The generated Json matches and is syntactically correct to the expected schema.";
    private static final String DEFAULT_INCORRECT_REASON =
            "The generated Json does not match the expected schema.";
    private static final String MULTIMODAL_RULES = """

            --- MULTIMODAL INPUT RULES ---
            - Treat image content as factual evidence.
            - Only reference visual details that are explicitly and clearly visible.
            - Do not infer or guess objects, text, or details not visibly present.
            - If an image is unclear or ambiguous, mark uncertainty explicitly.
            """;

    private static final ObjectMapper MAPPER = new ObjectMapper()
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
            .enable(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES)
            .enable(DeserializationFeature.FAIL_ON_NULL_CREATOR_PROPERTIES);

    private final EvaluationModel model;
    private final Class<?> expectedSchema;
    private final double threshold;
    private final boolean includeReason;
    private double score;
    private String reason;
    private boolean success;

    public JsonCorrectnessMetric(Class<?> expectedSchema) {
        this(expectedSchema, true);
    }

    public JsonCorrectnessMetric(EvaluationModel model, Class<?> expectedSchema) {
        this(model, expectedSchema, true, true, 0.5);
    }

    public JsonCorrectnessMetric(Class<?> expectedSchema, boolean includeReason) {
        this(expectedSchema, includeReason, true, 0.5);
    }

    public JsonCorrectnessMetric(Class<?> expectedSchema, boolean includeReason, boolean strictMode, double threshold) {
        this(null, expectedSchema, includeReason, strictMode, threshold);
    }

    public JsonCorrectnessMetric(
            EvaluationModel model,
            Class<?> expectedSchema,
            boolean includeReason,
            boolean strictMode,
            double threshold) {
        if (!Double.isFinite(threshold)) {
            throw new IllegalArgumentException("Json Correctness threshold must be finite");
        }
        this.model = model;
        this.expectedSchema = expectedSchema;
        this.includeReason = includeReason;
        this.threshold = strictMode ? 1.0 : threshold;
    }

    @Override
    public MetricResult measure(LlmTestCase testCase) {
        MetricUtils.checkLlmTestCaseParams(
                testCase,
                List.of(SingleTurnParam.INPUT, SingleTurnParam.ACTUAL_OUTPUT),
                name());

        score = isValid(testCase.actualOutput()) ? 1.0 : 0.0;
        reason = includeReason ? generateReason(testCase.actualOutput(), testCase.multimodal()) : null;
        success = score >= threshold;
        return new MetricResult(name(), score, threshold, success, reason);
    }

    public String name() {
        return "Json Correctness";
    }

    public double score() {
        return score;
    }

    public String reason() {
        return reason;
    }

    public boolean success() {
        return success;
    }

    private boolean isValid(String actualOutput) {
        try {
            MAPPER.readValue(actualOutput, expectedSchema);
            return true;
        } catch (Exception ignored) {
            return false;
        }
    }

    private String generateReason(String actualOutput, boolean multimodal) {
        if (score == 1.0) {
            return DEFAULT_CORRECT_REASON;
        }
        if (model == null) {
            return DEFAULT_INCORRECT_REASON;
        }
        return JsonCorrectnessSchemas.parseScoreReason(model.generate(generateReasonPrompt(actualOutput, multimodal)))
                .reason();
    }

    private String generateReasonPrompt(String actualOutput, boolean multimodal) {
        return """
                Based on the given generated json, generated by an LLM, and a boolean stating whether it is a valid JSON based on the expected json schema, give a reason why it is OR is not a valid Json.

                %s
                **
                IMPORTANT: Please make sure to only return in JSON format, with the 'reason' key providing the reason.
                Example JSON:
                {
                  "reason": "The generated Json is <is_valid_json> because <your_reason>."
                }

                If the json is not a valid one, your reason MUST compare `Expected Json Schema` and `Generated Json` in your reason. Keep it SHORT and CONCISE while being very FACTUAL and ACTIONABLE.
                **

                Generated Json:
                %s

                Expected Json Schema:
                %s

                Is Valid Json?
                false

                JSON:
                """.formatted(multimodal ? MULTIMODAL_RULES : "", actualOutput, expectedSchemaJson());
    }

    private String expectedSchemaJson() {
        var schema = new LinkedHashMap<String, Object>();
        schema.put("type", "object");
        var properties = new LinkedHashMap<String, Map<String, String>>();
        var required = new ArrayList<String>();
        if (expectedSchema.isRecord()) {
            for (var component : expectedSchema.getRecordComponents()) {
                properties.put(component.getName(), Map.of("type", jsonType(component.getType())));
                required.add(component.getName());
            }
        }
        schema.put("properties", properties);
        schema.put("required", required);
        try {
            return MAPPER.writeValueAsString(schema);
        } catch (JsonProcessingException e) {
            throw new IllegalArgumentException("Expected schema must be JSON serializable", e);
        }
    }

    private static String jsonType(Class<?> type) {
        if (type == String.class || type == Character.class || type == char.class) {
            return "string";
        }
        if (type == boolean.class || type == Boolean.class) {
            return "boolean";
        }
        if (type == int.class || type == long.class || type == short.class || type == byte.class
                || type == Integer.class || type == Long.class || type == Short.class || type == Byte.class) {
            return "integer";
        }
        if (type == float.class || type == double.class || type == Float.class || type == Double.class) {
            return "number";
        }
        return "object";
    }
}
